#ifndef INVLAUNCH_RESOURCE_H
#define INVLAUNCH_RESOURCE_H

#define IDI_MAIN 1001

#define IDC_MAIN_RESOLUTION 1002
#define IDC_MAIN_FULLSCREEN 1003
#define IDC_MAIN_LAUNCH 1004
#define IDC_MAIN_EXIT 1005
#define IDC_MAIN_LAUNCHERGRAPHIC 1006


// launcher graphic
#define IDB_LAUNCHER 1010

#endif